### PR TITLE
Create a map in the index page and load the geojson file

### PR DESCRIPTION
**Pull request by martavj**
- Added a map and loaded the geojson geometries. 
- Changed the style to center the filters

Screenshot 2021-10-30 at 16 10 44

//TO DO 
- Change the popup template
- Continue with the style of the index and add the list of all the results by default

### CODE REVIEW

**Comment by hhkaos** [comment]
I guess you are following here the mockup a provide at first, right?. Do you think this improves the UX?

**Comment by martavj** [comment]
Yes, I was following the original mockup. It is still work in progress. I
can't really tell. I think we can start from that mockup and make changes
after testing it and asking for feedback. Don't you think?

**Comment by hhkaos** [comment]
Ok! Let's do it like this 😁

**Review by hhkaos — COMMENTED** [review]
Everything fine!

**Pull request merged**
